import { describe, expect, it } from "vitest";
import { buildCertificatePdf } from "@/modules/records/certificate";

describe("buildCertificatePdf", () => {
  it("produces a valid PDF containing the record details", () => {
    const pdf = buildCertificatePdf({
      title: "Business Registration Certificate",
      subtitle: "Demo certificate issued by Corporate Affairs Commission",
      lines: [
        ["Record type", "Business Registration"],
        ["Reference", "CAC-CO-2026-000001"],
        ["Holder", "Aisha Bello"],
        ["Issue date", "2026-08-30"],
      ],
      footer: "This is a demonstration certificate generated by CivicOne.",
    });
    const text = pdf.toString("binary");
    expect(text.startsWith("%PDF-1.4")).toBe(true);
    expect(text).toContain("Business Registration Certificate");
    expect(text).toContain("CAC-CO-2026-000001");
    expect(pdf.length).toBeGreaterThan(300);
  });

  it("escapes parentheses in values", () => {
    const pdf = buildCertificatePdf({
      title: "Certificate (Demo)",
      subtitle: "Subtitle",
      lines: [["Holder", "Obi (Jr.)"]],
      footer: "Footer",
    });
    expect(pdf.toString("binary")).toContain("\\(");
  });
});
