import "server-only";
import type {
  DocumentCategory,
  RecordSource,
  RecordStatus,
  RecordVerificationStatus,
} from "@prisma/client";
import { db } from "@/server/db";
import { AppError } from "@/server/errors";
import { logAudit } from "@/server/audit";
import { requireUser } from "@/server/auth/session";
import { assertPermission, PERMISSIONS } from "@/server/rbac";
import { generateId } from "@/lib/id";
import { buildCertificatePdf } from "./certificate";
import { generateVerificationToken, getVerificationUrl } from "./qr-verification";

const RECORD_TYPE_BY_SLUG: Record<string, string> = {
  "business-registration": "Business Registration",
  "national-passport": "Passport",
  "driver-licence": "Driver's Licence",
};

const CERT_CATEGORY_BY_SLUG: Record<string, DocumentCategory> = {
  "business-registration": "BUSINESS",
  "national-passport": "IDENTITY",
  "driver-licence": "LICENCES",
};

const EXPIRY_YEARS_BY_SLUG: Record<string, number | null> = {
  "business-registration": null,
  "national-passport": 10,
  "driver-licence": 5,
};

export interface RecordCreateResult {
  recordId: string;
  certificateId: string | null;
  created: boolean;
}

export async function createRecordForApprovedApplication(
  applicationId: string,
): Promise<RecordCreateResult> {
  const existing = await db.governmentServiceRecord.findUnique({ where: { applicationId } });
  if (existing) return { recordId: existing.id, certificateId: null, created: false };

  const application = await db.application.findUnique({
    where: { id: applicationId },
    include: { service: { include: { provider: true } } },
  });
  if (!application) throw new AppError("Application not found.", { code: "NOT_FOUND" });

  const slug = application.service.slug;
  const recordType = RECORD_TYPE_BY_SLUG[slug] ?? application.service.name;
  const expiryYears = EXPIRY_YEARS_BY_SLUG[slug] ?? null;
  const now = new Date();
  const expiryDate = expiryYears
    ? new Date(now.getTime() + expiryYears * 365 * 24 * 60 * 60 * 1000)
    : null;

  const profile = await db.identityProfile.findUnique({ where: { userId: application.userId } });

  const recordId = generateId("rec");
  const certificateId = generateId("wdc");
  const verificationToken = generateVerificationToken(recordId, certificateId);
  const verificationUrl = getVerificationUrl(verificationToken);

  const record = await db.governmentServiceRecord.create({
    data: {
      id: recordId,
      userId: application.userId,
      serviceId: application.serviceId,
      providerId: application.service.providerId,
      applicationId: application.id,
      recordType,
      externalReference: application.providerRef,
      status: "ACTIVE",
      issueDate: now,
      expiryDate,
      registrationDate: now,
      verificationStatus: "GOVERNMENT_VERIFIED",
      source: "CIVICONE",
      metadata: {
        applicationReference: application.reference,
        verificationToken,
      },
    },
  });

  const pdf = buildCertificatePdf({
    title: `${recordType} Certificate`,
    subtitle: `Demo certificate issued by ${application.service.provider.name}`,
    lines: [
      ["Record type", recordType],
      ["Reference", application.providerRef ?? "—"],
      ["Holder", profile?.legalName ?? "—"],
      ["Issue date", now.toISOString().slice(0, 10)],
      ["Expiry date", expiryDate ? expiryDate.toISOString().slice(0, 10) : "N/A"],
      ["Application", application.reference],
    ],
    footer: "This is a demonstration certificate generated by CivicOne. Not an official government document.",
    verificationUrl,
  });

  const certificate = await db.walletDocument.create({
    data: {
      id: certificateId,
      userId: application.userId,
      recordId: record.id,
      category: CERT_CATEGORY_BY_SLUG[slug] ?? "OTHER",
      name: `${recordType} certificate`,
      fileName: `${slug}-certificate.pdf`,
      mimeType: "application/pdf",
      sizeBytes: pdf.length,
      fileData: pdf as unknown as Uint8Array<ArrayBuffer>,
      issuer: application.service.provider.name,
      issueDate: now,
      expiryDate,
      verificationStatus: "GOVERNMENT_VERIFIED",
      source: "CIVICONE",
    },
  });

  await logAudit({
    actorId: application.userId,
    action: "record.created",
    resourceType: "record",
    resourceId: record.id,
    metadata: { recordType, applicationReference: application.reference },
  });

  return { recordId: record.id, certificateId: certificate.id, created: true };
}

const EXPIRING_SOON_DAYS = 60;

export interface RecordCardView {
  id: string;
  recordType: string;
  serviceSlug: string;
  serviceName: string;
  providerName: string;
  providerAbbreviation: string | null;
  status: RecordStatus;
  verificationStatus: RecordVerificationStatus;
  source: RecordSource;
  externalReference: string | null;
  issueDate: Date | null;
  expiryDate: Date | null;
}

export interface WalletDocumentView {
  id: string;
  category: string;
  name: string;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  issuer: string | null;
  issueDate: Date | null;
  expiryDate: Date | null;
  verificationStatus: RecordVerificationStatus;
  source: RecordSource;
  createdAt: Date;
}

export interface MyServicesOverview {
  active: RecordCardView[];
  completed: RecordCardView[];
  expiringSoon: RecordCardView[];
  archived: RecordCardView[];
}

const recordSelect = {
  id: true,
  recordType: true,
  status: true,
  verificationStatus: true,
  source: true,
  externalReference: true,
  issueDate: true,
  expiryDate: true,
  createdAt: true,
  service: { select: { slug: true, name: true } },
  provider: { select: { name: true, abbreviation: true } },
} as const;

async function loadOwnedRecords() {
  const user = await requireUser();
  assertPermission(user.roleNames, PERMISSIONS.RECORDS_SELF);
  const rows = await db.governmentServiceRecord.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: "desc" },
    select: recordSelect,
  });
  return rows.map((row) => ({
    id: row.id,
    recordType: row.recordType,
    serviceSlug: row.service.slug,
    serviceName: row.service.name,
    providerName: row.provider.name,
    providerAbbreviation: row.provider.abbreviation,
    status: row.status,
    verificationStatus: row.verificationStatus,
    source: row.source,
    externalReference: row.externalReference,
    issueDate: row.issueDate,
    expiryDate: row.expiryDate,
  }));
}

export async function getMyServicesOverview(): Promise<MyServicesOverview> {
  const cards = await loadOwnedRecords();
  const now = new Date();
  const soon = new Date(now.getTime() + EXPIRING_SOON_DAYS * 24 * 60 * 60 * 1000);
  return {
    active: cards.filter((c) => c.status === "ACTIVE"),
    completed: cards.filter((c) => c.status === "COMPLETED"),
    expiringSoon: cards.filter(
      (c) => c.expiryDate !== null && c.expiryDate! > now && c.expiryDate! <= soon,
    ),
    archived: cards.filter((c) => c.status === "ARCHIVED"),
  };
}

export interface RecordDetailView {
  id: string;
  recordType: string;
  serviceSlug: string;
  serviceName: string;
  serviceSummary: string;
  providerName: string;
  providerAbbreviation: string | null;
  officialUrl: string | null;
  status: RecordStatus;
  verificationStatus: RecordVerificationStatus;
  source: RecordSource;
  externalReference: string | null;
  issueDate: Date | null;
  expiryDate: Date | null;
  verificationToken: string | null;
  registrationDate: Date | null;
  createdAt: Date;
  documents: WalletDocumentView[];
  application: {
    id: string;
    reference: string;
    status: string;
    timeline: Array<{ fromStatus: string | null; toStatus: string; reason: string | null; createdAt: Date }>;
  } | null;
}

export async function getRecordById(id: string): Promise<RecordDetailView> {
  const user = await requireUser();
  assertPermission(user.roleNames, PERMISSIONS.RECORDS_SELF);
  const record = await db.governmentServiceRecord.findUnique({
    where: { id },
    include: {
      service: { select: { slug: true, name: true, summary: true } },
      provider: { select: { name: true, abbreviation: true, officialUrl: true } },
      application: { include: { statusHistory: { orderBy: { createdAt: "asc" } } } },
      documents: { orderBy: { createdAt: "asc" } },
    },
  });
  if (!record || record.userId !== user.id) {
    throw new AppError("Record not found.", { code: "NOT_FOUND" });
  }
  return {
    id: record.id,
    recordType: record.recordType,
    serviceSlug: record.service.slug,
    serviceName: record.service.name,
    serviceSummary: record.service.summary,
    providerName: record.provider.name,
    providerAbbreviation: record.provider.abbreviation,
    officialUrl: record.provider.officialUrl,
    status: record.status,
    verificationStatus: record.verificationStatus,
    source: record.source,
    externalReference: record.externalReference,
    issueDate: record.issueDate,
    expiryDate: record.expiryDate,
    verificationToken:
      record.metadata && typeof record.metadata === "object" && "verificationToken" in record.metadata
        ? (record.metadata.verificationToken as string)
        : null,
    registrationDate: record.registrationDate,
    createdAt: record.createdAt,
    documents: record.documents.map((d) => ({
      id: d.id,
      category: d.category,
      name: d.name,
      fileName: d.fileName,
      mimeType: d.mimeType,
      sizeBytes: d.sizeBytes,
      issuer: d.issuer,
      issueDate: d.issueDate,
      expiryDate: d.expiryDate,
      verificationStatus: d.verificationStatus,
      source: d.source,
      createdAt: d.createdAt,
    })),
    application: record.application
      ? {
          id: record.application.id,
          reference: record.application.reference,
          status: record.application.status,
          timeline: record.application.statusHistory.map((h) => ({
            fromStatus: h.fromStatus,
            toStatus: h.toStatus,
            reason: h.reason,
            createdAt: h.createdAt,
          })),
        }
      : null,
  };
}
