import "server-only";
import type { DocumentCategory } from "@prisma/client";
import { db } from "@/server/db";
import { AppError } from "@/server/errors";
import { logAudit } from "@/server/audit";
import { generateId } from "@/lib/id";
import { buildCertificatePdf } from "./certificate";

const RECORD_TYPE_BY_SLUG: Record<string, string> = {
  "business-registration": "Business Registration",
  "national-passport": "Passport",
  "driver-licence": "Driver's Licence",
};

const CERT_CATEGORY_BY_SLUG: Record<string, DocumentCategory> = {
  "business-registration": "BUSINESS",
  "national-passport": "IDENTITY",
  "driver-licence": "LICENCES",
};

const EXPIRY_YEARS_BY_SLUG: Record<string, number | null> = {
  "business-registration": null,
  "national-passport": 10,
  "driver-licence": 5,
};

export interface RecordCreateResult {
  recordId: string;
  certificateId: string | null;
  created: boolean;
}

export async function createRecordForApprovedApplication(
  applicationId: string,
): Promise<RecordCreateResult> {
  const existing = await db.governmentServiceRecord.findUnique({ where: { applicationId } });
  if (existing) return { recordId: existing.id, certificateId: null, created: false };

  const application = await db.application.findUnique({
    where: { id: applicationId },
    include: { service: { include: { provider: true } } },
  });
  if (!application) throw new AppError("Application not found.", { code: "NOT_FOUND" });

  const slug = application.service.slug;
  const recordType = RECORD_TYPE_BY_SLUG[slug] ?? application.service.name;
  const expiryYears = EXPIRY_YEARS_BY_SLUG[slug] ?? null;
  const now = new Date();
  const expiryDate = expiryYears
    ? new Date(now.getTime() + expiryYears * 365 * 24 * 60 * 60 * 1000)
    : null;

  const profile = await db.identityProfile.findUnique({ where: { userId: application.userId } });

  const record = await db.governmentServiceRecord.create({
    data: {
      id: generateId("rec"),
      userId: application.userId,
      serviceId: application.serviceId,
      providerId: application.service.providerId,
      applicationId: application.id,
      recordType,
      externalReference: application.providerRef,
      status: "ACTIVE",
      issueDate: now,
      expiryDate,
      registrationDate: now,
      verificationStatus: "GOVERNMENT_VERIFIED",
      source: "CIVICONE",
      metadata: { applicationReference: application.reference },
    },
  });

  const pdf = buildCertificatePdf({
    title: `${recordType} Certificate`,
    subtitle: `Demo certificate issued by ${application.service.provider.name}`,
    lines: [
      ["Record type", recordType],
      ["Reference", application.providerRef ?? "—"],
      ["Holder", profile?.legalName ?? "—"],
      ["Issue date", now.toISOString().slice(0, 10)],
      ["Expiry date", expiryDate ? expiryDate.toISOString().slice(0, 10) : "N/A"],
      ["Application", application.reference],
    ],
    footer: "This is a demonstration certificate generated by CivicOne. Not an official government document.",
  });

  const certificate = await db.walletDocument.create({
    data: {
      id: generateId("wdc"),
      userId: application.userId,
      recordId: record.id,
      category: CERT_CATEGORY_BY_SLUG[slug] ?? "OTHER",
      name: `${recordType} certificate`,
      fileName: `${slug}-certificate.pdf`,
      mimeType: "application/pdf",
      sizeBytes: pdf.length,
      fileData: pdf as unknown as Uint8Array<ArrayBuffer>,
      issuer: application.service.provider.name,
      issueDate: now,
      expiryDate,
      verificationStatus: "GOVERNMENT_VERIFIED",
      source: "CIVICONE",
    },
  });

  await logAudit({
    actorId: application.userId,
    action: "record.created",
    resourceType: "record",
    resourceId: record.id,
    metadata: { recordType, applicationReference: application.reference },
  });

  return { recordId: record.id, certificateId: certificate.id, created: true };
}
